katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

todolist/urls.py
from django.urls import path
from todolist.views import delete_task, show_todolist, register, login_user, logout_user, create_task, toggle_task_status, delete_task, get_json, create_task_ajax, delete_task_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('toggle-status/<int:id>', toggle_task_status, name='toggle_status'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    path('json/', get_json, name='get_json'),
    path('add/', create_task_ajax, name='add'),
    path('delete/<int:id>', delete_task_ajax, name='delete'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class TaskForm(forms.Form):
    title = forms.CharField(label='Title', max_length=255)
    description = forms.CharField(widget= forms.Textarea, required=False)

todolist/views.py
from cmath import isfinite
import datetime
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core import serializers
from django.urls import reverse
from django.shortcuts import render
from todolist.models import Task
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from todolist.forms import TaskForm
from django.views.decorators.csrf import csrf_exempt



@login_required(login_url='/todolist/login/')
def show_todolist(request):
    context = {
        'username': request.user.get_username(),
    }

    return render(request, 'todolist.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun berhasil dibuat!')
            return redirect('todolist:login')
        
    context = {'form' : form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse('todolist:show_todolist'))
            # response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau password salah!')
    
    context = {}
    return render(request, 'login.html', context)

@login_required(login_url='/todolist/login/')
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    # response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        date = datetime.datetime.today()
        description = request.POST.get('description')
        form = TaskForm(request.POST)

        Task.objects.create(
            user = request.user,
            title = title,
            description = description,
            date = date,
            is_finished = False,
        )

        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    else:
        form = TaskForm()
        messages.info(request, 'Input salah')
    
    context = {'form' : form}
    return render(request, 'create_task.html', context)

@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.datetime.today()

        Task.objects.create(
            user = request.user,
            title = title,
            description = description,
            date = date,
            is_finished = False,
        )

        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    else:
        messages.info(request, "INPUT SALAH")

    return (request, 'show_todolist.html')
    
    

@login_required(login_url='/todolist/login')
def delete_task(request, id):
    task = Task.objects.get(id=id, user=request.user)
    task.delete()

    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete_task_ajax(request, id):
    task = Task.objects.get(id=id, user=request.user)
    task.delete()

    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url='/todolist/login')
def toggle_task_status(request, id):
    task = Task.objects.get(id=int(id), user=request.user)
    task.is_finished = not task.is_finished
    task.save(update_fields=['is_finished'])

    return HttpResponseRedirect(reverse("todolist:show_todolist"))

@login_required(login_url='/todolist/login')
def get_json(request):
    data = Task.objects.filter(user=request.user)

    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/templates/create_task.html
{% extends 'base.html' %}
{% block meta %}
{% endblock meta %}

{% block content %}
<div class="flex flex-col justify-center items-center h-screen min-w-min">
    <div class="pb-4">
        <p class="text-3xl text-green-500 font-bold">
            Create Task
        </p>
    </div>

    <div>
        <form action="/todolist/create-task/" method="post">
            {% csrf_token %}
            <table>
                <div class="">
                    <tr>
                        <td>
                            <p class="text-lg pr-4">Title</p>
                            <input type="text" name="title" placeholder="Enter title" 
                            class="border-1 rounded 
                                focus:border-2 focus:border-green-700 mb-2">
                        </td>
                    </tr>
                </div>
                        
                <tr>
                    <td>
                        <p class="text-lg pr-4">Description</p>
                        <input type="text" name="description" placeholder="Enter description" 
                            class="border-1 rounded 
                            focus:border-2 focus:border-green-700 mb-2">
                    </td>
                </tr>
                <tr class="flex flex-row justify-center items-center">
                    <td>
                        <button class="text-white bg-gray-700 
                        hover:bg-gray-800 focus:ring-4 focus:ring-gray-300 
                        font-medium rounded-lg text-sm px-5 py-2.5 mr-2 
                        mb-2 dark:bg-gray-600 dark:hover:bg-gray-700 
                        focus:outline-none dark:focus:ring-gray-800
                        my-4">
                            <a href="{% url 'todolist:show_todolist' %}">
                                Back
                            </a>
                        </button>
                    </td>
                    <td>
                        <input type="submit" value="Add Task" class="text-white bg-green-700 
                        hover:bg-green-800 focus:ring-4 focus:ring-green-300 
                        font-medium rounded-lg text-sm px-5 py-2.5 mr-2 
                        mb-2 dark:bg-green-600 dark:hover:bg-green-700 
                        focus:outline-none dark:focus:ring-green-800
                        my-4">
                    </td>
                </tr>
                <tr>

                </tr>
            </table>
        </form>
    </div>
</div>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}
{% block meta %}
{% endblock meta %}

{% block content %}

<div class="flex flex-col justify-center items-center h-screen min-w-min">
    <div class="pb-4">
        <p class="text-4xl text-green-500 font-bold">
            Login
        </p>
    </div>
    <div>
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td class="pb-2 pt-4">
                        <p class="text-lg pr-4 pb-1">Username</p>
                        <input type="text" name="username" placeholder="" size="20"
                        class="border-1 rounded 
                            focus:border-1.5 focus:border-green-600">
                    </td>
                </tr>
                <tr>
                    <td class="pb-2">
                        <p class="text-lg pr-4 pb-1">Password</p>
                        <input type="password" name="password" placeholder="" size="20" 
                            class="border-1 rounded 
                            focus:border-1.5
                            focus:border-green-600">
                    </td>
                </tr>
                        
                <tr class="flex justify-center items-center pt-4">
                    <td>
                        <button class="text-white bg-green-700 
                        hover:bg-green-800 focus:ring-4 focus:ring-green-300 
                        font-medium rounded-lg text-sm px-6 py-1.5 mr-2
                        mb-2 dark:bg-green-600 dark:hover:bg-green-700 
                        focus:outline-none dark:focus:ring-green-800">
                            <input class="text-xl mb-2" type="submit" value="Login">
                        </button>
                    </td>
                </tr>
                <tr>
                </tr>
            </table>
        </form>
    </div>

    <div class="flex flex-row m-4">
        <div class="pr-2">
            Belum mempunyai akun? 
        </div>
        <div class="text-green-500 font-normal hover:underline hover:font-bold hover:text-green-600">
            <a href="{% url 'todolist:register' %}">Buat Akun</a>
        </div>
    </div>

        <!-- {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}      -->

        
    
</div>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
{% endblock meta %}
    
{% block content %}  
<div class="flex flex-col justify-center items-center h-screen min-w-min">
    <div class="pb-4 px-4">
        <!-- Form registrasi -->
        <p class="text-4xl text-green-500 font-bold text-center">
            Register Account
        </p>
    </div>

    <div>
        <!-- Form -->
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                <tr>
                    <!-- Username -->
                    <td class="pb-2 pt-4 px-2">
                        <p class="text-lg pr-4 pb-1">
                            {{form.username.label_tag}}
                        </p>
                        <div class="border-1 rounded-lg 
                        focus:border-1.5 focus:border-green-600">
                            {{form.username}}
                        </div>
                    </td>
                </tr>
                <tr>
                    <!-- Password -->
                    <td class="pb-2 px-2">
                        <p class="text-lg pr-4 pb-1">
                            {{form.password1.label_tag}}
                        </p>
                        <div class="border-1 rounded-lg 
                        focus:border-1.5 focus:border-green-600">
                            {{form.password1}}
                        </div>
                    </td>
                </tr>
                <tr>
                    <!-- Confirm password -->
                    <td class="pb-2 px-2">
                        <p class="text-lg pr-4 pb-1">
                            {{form.password2.label_tag}}
                        </p>
                        <div class="border-1 rounded-lg 
                        focus:border-1.5 focus:border-green-600">
                            {{form.password2}}
                        </div>
                    </td>
                </tr>
                <tr class="flex justify-center items-center pt-4 px-2">
                    <!-- Back button -->
                    <td>
                        <button class="text-white bg-gray-700 
                        hover:bg-gray-800 focus:ring-4 focus:ring-gray-300 
                        font-medium rounded-lg text-sm px-5 py-2.5 mr-2 
                        mb-2 dark:bg-gray-600 dark:hover:bg-gray-700 
                        focus:outline-none dark:focus:ring-gray-800
                        my-4">
                            <a href="{% url 'todolist:show_todolist' %}">Back</a>
                        </button>
                    </td>
                    <!-- Registration button -->
                    <td>
                        <input type="submit"name="submit" value="Register" class="text-white bg-green-700 
                        hover:bg-green-800 focus:ring-4 focus:ring-green-300 
                        font-medium rounded-lg text-sm px-5 py-2.5 mr-2 
                        mb-2 dark:bg-green-600 dark:hover:bg-green-700 
                        focus:outline-none dark:focus:ring-green-800
                        my-4">
                    </td>
                </tr>

                {% if messages %}  
                    <ul class="text-md py-2">   
                        {% for message in messages %}  
                            <li>{{ message }}</li>  
                            {% endfor %}  
                    </ul>   
                {% endif %}
            </table>
        </form>
    </div>
</div>

<!-- <div class = "login">
    
    <h1>Form Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    

</div>   -->

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
{% endblock meta %}

{% block content %}

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <style>
        #overlay {
            position: fixed; 
            opacity: 0;
            top: 0; 
            left: 0; 
            right: 0;
            bottom: 0;
            height: 100%; 
            width: 100%; 
            background-color: rgba(0,0,0,0.5);
            transition: 250ms ease-in-out;
            pointer-events: none;
        }
        #overlay.active {
            opacity: 1;
            pointer-events: all;
        }

        #modal {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) scale(0);
            border: 1px solid black;
            border-radius: 6px;
            z-index: 10;
            background-color: white;
            width: 500px;
            max-width: 80%;
            transition: 250ms ease-in-out;
        }

        #modal.active {
            transform: translate(-50%, -50%) scale(1);
        }
    </style>
</head>
<div id="app-container" style="min-width: 250px;">
    <nav class="flex flex-row bg-green-500 shadow py-4 items-center fixed top-0" 
            style="background-color: white; width: 100%; justify-content: space-between; padding: 1rem .5rem;
                    border-bottom: 1px solid lightgray;">
        <div class="text-xl text-green-500 font-bold px-2">
            {{username}}
        </div> 
    
        <button 
            id="add-task"
            data-modal-target="#modal"
            type="button"
            class="text-white bg-green-700 
            hover:bg-green-800 focus:ring-4 focus:ring-green-300 
            font-medium rounded-lg text-sm py-2 px-2
          dark:bg-green-600 dark:hover:bg-green-700 
            focus:outline-none dark:focus:ring-green-800">
            Add Task
        </button>
    
        <div class="flex items-center px-4">
            <button class="text-white bg-gray-700 
            hover:bg-gray-800 focus:ring-4 focus:ring-gray-300 
            font-medium rounded-lg text-sm py-2 px-2
            dark:bg-gray-600 dark:hover:bg-gray-700 
            focus:outline-none dark:focus:ring-gray-800">
                <a href="{% url 'todolist:logout' %}" style="width: 100%">
                    Logout
                </a>
            </button>
        </div>
    </nav>

    <!-- App -->
    <div id="app" class="flex flex-col justify-center items-center mt-4" style="padding-top: 4rem;">
        <div id="overlay" class=""></div>
        
        <div id="modal" class="px-4 py-2">
            <div id="modal-header" class="flex flex-row items-center py-2 border-b-1 border-solid border-black">
                <div id="modal-header-title" class="text-xl font-bold text-green-700">
                    Fill Task Details
                </div>
                <button id="modal-close-button" style="margin-left: auto;" data-close-button
                    class="cursor-pointer border-none outline-none bg-none text-3xl font-bold text-rose-700">
                    &times;
                </button>
            </div>
            <div id="modal-body" class="flex flex-col py-2">
                <div class="flex flex-col pb-4">
                    <label class="text-lg pb-2">Title</label>
                    <input required id="title-input" type="text" name="title" placeholder="Enter title" 
                    class="border-1 rounded focus:border-2 focus:border-green-700">
                </div>
                <div class="flex flex-col">
                    <label class="text-lg pb-2">Description</label>
                    <input required id="description-input" type="text" name="description" placeholder="Enter description" 
                                    class="border-1 rounded focus:border-2 focus:border-green-700 mb-2">
                </div>
                <div id="modal-cta" class="flex flex-col justify-center items-center">
                    <button id="modal-add-task" type="submit" class="text-white bg-green-700 
                    hover:bg-green-800 focus:ring-4 focus:ring-green-300 
                    font-medium rounded-lg text-sm px-5 py-2.5 mr-2 
                    mb-2 dark:bg-green-600 dark:hover:bg-green-700 
                    focus:outline-none dark:focus:ring-green-800
                    my-4">
                        Add Task
                    </button>
                </div>
            </div>
        </div>       

        <div id="top-section"></div>
        
    
        <div id="todolist" class="m-4 w-6/12">

        </div>
    
        
    </div>
</div>

<script type="text/javascript">
    const modal = document.querySelectorAll('#modal');
    const openModalBtn = document.querySelectorAll("[data-modal-target]");
    const closeModalBtn = document.querySelectorAll("[data-close-button]");
    const overlay = document.getElementById("overlay");
    const modalAddTask = document.getElementById("modal-add-task");

    openModalBtn.forEach(button => {
        button.addEventListener('click', () => {
            const modal = document.querySelector(button.dataset.modalTarget);
            openModal(modal);
        });
    });

    closeModalBtn.forEach(button => {
        button.addEventListener('click', () => {
            const modal = button.closest('#modal');
            closeModal(modal);
        });
    });
    
    overlay.addEventListener('click', () => {
        const modals = document.querySelectorAll('#modal.active');
        modals.forEach(modal => {
            closeModal(modal);
        });
    });

    modalAddTask.addEventListener('click', () => {
        const titleVal = $("#title-input").val();
        const descVal = $("#description-input").val();

        if (titleVal == "" || descVal == "") {
            if ($("#field-error").length >  0) {
                $("#field-error").remove()
            }
            $("#modal-cta").prepend(`<p id="field-error" class="text-lg py-2 font-bold text-green-500">Please fill the empty fields!</p>`);
        } else {
            $.post({
                url: 'add/',
                type: 'post',
                data: {
                    'title': titleVal,
                    'description': descVal,
                },
                success: [createSections, loadTasksList],
            });


            // Clear input box values
            $("#title-input").val("")
            $("#description-input").val("")
            $("#field-error").remove()
    
            // Close modal
            const modal = modalAddTask.closest("#modal.active");
            closeModal(modal)
        }
    })   
       
    // Helper functions
    function openModal(modal) {
        if (modal == null) {
            return;
        }

        modal.classList.add('active');
        overlay.classList.add('active');
    }

    function closeModal(modal) {
        if (modal == null) {
            return;
        }

        modal.classList.remove('active');
        overlay.classList.remove('active');
    }

    function createSections() {
        $.getJSON('/todolist/json/', function(data) {
            /* Control program section logic */
            var activeAmount = 0;
            var finishedAmount = 0;
    
            for (var i = 0; i < data.length; i++) {
                if (data[i].fields.is_finished) {
                    finishedAmount++;
                } else {
                    activeAmount++;
                }
            }

            if (activeAmount == 0 && finishedAmount == 0 && $("#nty").length == 0) {
                $("#top-section").append(`<p id="nty" class="text-2xl text-green-500 font-bold pt-4">No tasks yet. Start adding!</p>`);
            } else {
                if ($("#top-section").length > 0) {
                    $("#top-section").empty();
                }
                if (activeAmount > 0 && $("#section-active-task").length == 0) {

                    $("#todolist").append(
                        `<div id="section-active-task" class="flex flex-col justify-center items-center">
                            <div class="text-3xl">Active Tasks</div>
                            <div class="text-xl pb-4 pt-2 px-2">Let's do this! 
                                <span class="text-gray-500 font-bold">
                                    ${activeAmount}
                                </span> task left.
                            </div>
                            <div id="active-tasks" class="flex flex-col justify-center items-center pb-4">
                            </div>
                        </div>`  
                        
                    );
                } 
    
                if (finishedAmount > 0 && $("#section-finished-task").length == 0) {
                    $("#todolist").append(
                        `<div id="section-finished-task" class="flex flex-col justify-center items-center pb-4">
                            <div class="flex flex-col justify-center items-center">
                                <div class="text-3xl">Finished Tasks</div>
                                <div class="text-xl pb-4 pt-2 px-2">Congrats! You have finished
                                    <span class="text-green-500 font-bold">
                                        ${finishedAmount}
                                    </span> tasks.
                                </div>
                            </div>      
                            
                            <div id="finished-tasks" class="flex flex-col justify-center items-center">  
                            </div>
                        </div>`
                    );
                }
            }
        });
    }

    function loadTasksList() {
        $.getJSON('/todolist/json/', function(data) {     
            /* Display task cards */
            
            // Empty the current task containers
            $('#active-tasks').empty();
            $('#finished-tasks').empty();
            
            for (var i = 0; i < data.length; i++) {
                var isFinished = data[i].fields.is_finished;
                var taskItem = `<div class="flex flex-col grow p-6 m-2 min-w-min bg-white rounded-lg border border-gray-200 shadow-md w-6/12 hover:bg-gray-200 hover:shadow-xl">
                        <p class="mb-2 text-md font-bold tracking-tight text-black-900 w-40 md:w-80">${data[i].fields.title}</p>
    
                        ${isFinished ? 
                            `<p class="mb-3 text-sm font-bold text-green-500">
                                Completed
                            </p>`
                            :
                            `<p class="mb-3 text-sm font-bold text-gray-500">
                                Active
                            </p>`
                        }
                        </p>
                        <p class="mb-3 text-sm font-normal text-gray-700">
                            ${data[i].fields.date}
                        </p>
                        <p class="mb-3 text-sm font-normal text-gray-700 max-w-xs">
                            ${data[i].fields.description}
                        </p>
                        <div class="flex flex-row last:mt-auto last:pt-4">
                            ${isFinished ?
                                `<button type="submit" class="text-gray-700 hover:text-white border 
                                    border-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300
                                    font-medium rounded text-sm px-2 py-1
                                    text-center mr-1 mb-1 dark:border-gray-500 dark:text-gray-500 
                                    dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800">
                                        <a href="/todolist/toggle-status/${data[i].pk}">
                                            Unfinish
                                        </a>
                                </button>`
                                :
                                `<button type="submit" class="text-green-700 hover:text-white border 
                                border-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300
                                font-medium rounded text-sm px-2 py-1
                                text-center mr-1 mb-1 dark:border-green-500 dark:text-green-500 
                                dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-800">
                                    <a href="/todolist/toggle-status/${data[i].pk}">
                                        Finish
                                    </a>
                                </button>`
                            }
                            <button type="submit" class="text-rose-700 hover:text-white border 
                            border-rose-700 hover:bg-rose-800 focus:ring-4 focus:outline-none focus:ring-rose-300
                            font-medium rounded text-sm px-2 py-1 
                            text-center mr-1 mb-1 dark:border-rose-500 dark:text-rose-500 
                            dark:hover:text-white dark:hover:bg-rose-600 dark:focus:ring-rose-800">
                                <a href="/todolist/delete/${data[i].pk}">
                                    Delete
                                </a>
                            </button>
                        </div>
                    </div>`;
                
                if (isFinished) {
                    $("#finished-tasks").append(taskItem);
                } else {
                    $("#active-tasks").append(taskItem);
                }
            }
        });
    }

    createSections();
    loadTasksList();
</script>
{% endblock content %}